"""
NeoSim Configuration Schema

Defines the YAML configuration structure for GTM simulations.
All simulations are driven by this config.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from pathlib import Path
import yaml


@dataclass
class ProductConfig:
    """Product definition."""
    name: str
    description: str
    category: str  # SaaS, DevTool, Consumer, Marketplace, etc.
    stage: str  # pre-launch, beta, launched
    unique_value_prop: str
    key_features: List[str] = field(default_factory=list)
    tech_stack: List[str] = field(default_factory=list)


@dataclass
class ICPPersona:
    """Ideal Customer Profile persona."""
    name: str  # e.g., "Technical Founder", "Growth PM"
    role: str
    company_size: str  # startup, smb, enterprise
    pain_points: List[str]
    goals: List[str]
    objection_tendencies: List[str] = field(default_factory=list)
    budget_range: str = "unknown"
    decision_speed: str = "medium"  # fast, medium, slow


@dataclass
class PricingTier:
    """Single pricing tier."""
    name: str
    price: float  # monthly, 0 for free
    billing: str = "monthly"  # monthly, yearly, one-time
    features: List[str] = field(default_factory=list)
    limits: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PricingConfig:
    """Pricing strategy configuration."""
    model: str  # freemium, free-trial, paid-only, usage-based
    tiers: List[PricingTier] = field(default_factory=list)
    trial_days: int = 0
    anchor_price: Optional[float] = None  # psychological anchor


@dataclass
class ChannelConfig:
    """Distribution channel configuration."""
    name: str  # organic-social, paid-ads, community, outbound, seo, partnerships
    priority: int = 1  # 1-5, higher = more focus
    budget_allocation: float = 0.0  # percentage or absolute
    existing_presence: str = "none"  # none, minimal, moderate, strong
    strategy_notes: str = ""


@dataclass
class CompetitorConfig:
    """Competitor definition."""
    name: str
    positioning: str  # how they position themselves
    pricing: str  # rough pricing info
    strengths: List[str] = field(default_factory=list)
    weaknesses: List[str] = field(default_factory=list)
    market_share: str = "unknown"  # dominant, significant, emerging, niche


@dataclass
class SimulationParams:
    """Simulation parameters."""
    cycles: int = 30  # number of simulation cycles
    buyer_agents: int = 20  # number of buyer agents
    competitor_agents: int = 3
    channel_agents: int = 5
    cycle_unit: str = "week"  # day, week, month
    randomness: float = 0.2  # 0-1, variance in agent decisions


@dataclass
class NeoSimConfig:
    """
    Complete NeoSim project configuration.

    This is the root config that drives all simulations.
    Generated by `neosim init` and stored as neosim.yaml.
    """
    # Metadata
    version: str = "1.0"
    project_name: str = "My GTM Strategy"
    created_at: str = ""

    # Core configs
    product: ProductConfig = None
    icp_personas: List[ICPPersona] = field(default_factory=list)
    pricing: PricingConfig = None
    channels: List[ChannelConfig] = field(default_factory=list)
    competitors: List[CompetitorConfig] = field(default_factory=list)

    # Simulation settings
    simulation: SimulationParams = field(default_factory=SimulationParams)

    # LLM settings
    llm_provider: str = "anthropic"  # anthropic, openai
    llm_model: str = "claude-sonnet-4-20250514"

    def validate(self) -> List[str]:
        """Validate config and return list of issues."""
        issues = []

        if not self.product:
            issues.append("Product configuration is required")
        elif not self.product.name:
            issues.append("Product name is required")
        elif not self.product.description:
            issues.append("Product description is required")

        if not self.icp_personas:
            issues.append("At least one ICP persona is required")

        if not self.pricing:
            issues.append("Pricing configuration is required")
        elif not self.pricing.tiers:
            issues.append("At least one pricing tier is required")

        if not self.channels:
            issues.append("At least one distribution channel is required")

        return issues

    def is_valid(self) -> bool:
        """Check if config is valid for simulation."""
        return len(self.validate()) == 0


def load_config(path: Path = None) -> NeoSimConfig:
    """
    Load NeoSim configuration from YAML file.

    Args:
        path: Path to config file. Defaults to ./neosim.yaml

    Returns:
        Loaded NeoSimConfig

    Raises:
        FileNotFoundError: If config file doesn't exist
        ValueError: If config is invalid
    """
    if path is None:
        path = Path.cwd() / "neosim.yaml"

    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with open(path, 'r') as f:
        data = yaml.safe_load(f)

    return _dict_to_config(data)


def save_config(config: NeoSimConfig, path: Path = None) -> Path:
    """
    Save NeoSim configuration to YAML file.

    Args:
        config: Configuration to save
        path: Path to save to. Defaults to ./neosim.yaml

    Returns:
        Path where config was saved
    """
    if path is None:
        path = Path.cwd() / "neosim.yaml"

    data = _config_to_dict(config)

    with open(path, 'w') as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    return path


def _dict_to_config(data: Dict) -> NeoSimConfig:
    """Convert dictionary to NeoSimConfig."""
    config = NeoSimConfig(
        version=data.get('version', '1.0'),
        project_name=data.get('project_name', 'My GTM Strategy'),
        created_at=data.get('created_at', ''),
        llm_provider=data.get('llm_provider', 'anthropic'),
        llm_model=data.get('llm_model', 'claude-sonnet-4-20250514'),
    )

    # Product
    if 'product' in data:
        p = data['product']
        config.product = ProductConfig(
            name=p.get('name', ''),
            description=p.get('description', ''),
            category=p.get('category', 'SaaS'),
            stage=p.get('stage', 'pre-launch'),
            unique_value_prop=p.get('unique_value_prop', ''),
            key_features=p.get('key_features', []),
            tech_stack=p.get('tech_stack', []),
        )

    # ICP Personas
    config.icp_personas = []
    for persona in data.get('icp_personas', []):
        config.icp_personas.append(ICPPersona(
            name=persona.get('name', ''),
            role=persona.get('role', ''),
            company_size=persona.get('company_size', 'startup'),
            pain_points=persona.get('pain_points', []),
            goals=persona.get('goals', []),
            objection_tendencies=persona.get('objection_tendencies', []),
            budget_range=persona.get('budget_range', 'unknown'),
            decision_speed=persona.get('decision_speed', 'medium'),
        ))

    # Pricing
    if 'pricing' in data:
        pr = data['pricing']
        tiers = []
        for tier in pr.get('tiers', []):
            tiers.append(PricingTier(
                name=tier.get('name', ''),
                price=tier.get('price', 0),
                billing=tier.get('billing', 'monthly'),
                features=tier.get('features', []),
                limits=tier.get('limits', {}),
            ))
        config.pricing = PricingConfig(
            model=pr.get('model', 'freemium'),
            tiers=tiers,
            trial_days=pr.get('trial_days', 0),
            anchor_price=pr.get('anchor_price'),
        )

    # Channels
    config.channels = []
    for ch in data.get('channels', []):
        config.channels.append(ChannelConfig(
            name=ch.get('name', ''),
            priority=ch.get('priority', 1),
            budget_allocation=ch.get('budget_allocation', 0),
            existing_presence=ch.get('existing_presence', 'none'),
            strategy_notes=ch.get('strategy_notes', ''),
        ))

    # Competitors
    config.competitors = []
    for comp in data.get('competitors', []):
        config.competitors.append(CompetitorConfig(
            name=comp.get('name', ''),
            positioning=comp.get('positioning', ''),
            pricing=comp.get('pricing', ''),
            strengths=comp.get('strengths', []),
            weaknesses=comp.get('weaknesses', []),
            market_share=comp.get('market_share', 'unknown'),
        ))

    # Simulation params
    if 'simulation' in data:
        sim = data['simulation']
        config.simulation = SimulationParams(
            cycles=sim.get('cycles', 30),
            buyer_agents=sim.get('buyer_agents', 20),
            competitor_agents=sim.get('competitor_agents', 3),
            channel_agents=sim.get('channel_agents', 5),
            cycle_unit=sim.get('cycle_unit', 'week'),
            randomness=sim.get('randomness', 0.2),
        )

    return config


def _config_to_dict(config: NeoSimConfig) -> Dict:
    """Convert NeoSimConfig to dictionary for YAML serialization."""
    data = {
        'version': config.version,
        'project_name': config.project_name,
        'created_at': config.created_at,
        'llm_provider': config.llm_provider,
        'llm_model': config.llm_model,
    }

    # Product
    if config.product:
        data['product'] = {
            'name': config.product.name,
            'description': config.product.description,
            'category': config.product.category,
            'stage': config.product.stage,
            'unique_value_prop': config.product.unique_value_prop,
            'key_features': config.product.key_features,
            'tech_stack': config.product.tech_stack,
        }

    # ICP Personas
    data['icp_personas'] = []
    for persona in config.icp_personas:
        data['icp_personas'].append({
            'name': persona.name,
            'role': persona.role,
            'company_size': persona.company_size,
            'pain_points': persona.pain_points,
            'goals': persona.goals,
            'objection_tendencies': persona.objection_tendencies,
            'budget_range': persona.budget_range,
            'decision_speed': persona.decision_speed,
        })

    # Pricing
    if config.pricing:
        tiers = []
        for tier in config.pricing.tiers:
            tiers.append({
                'name': tier.name,
                'price': tier.price,
                'billing': tier.billing,
                'features': tier.features,
                'limits': tier.limits,
            })
        data['pricing'] = {
            'model': config.pricing.model,
            'tiers': tiers,
            'trial_days': config.pricing.trial_days,
            'anchor_price': config.pricing.anchor_price,
        }

    # Channels
    data['channels'] = []
    for ch in config.channels:
        data['channels'].append({
            'name': ch.name,
            'priority': ch.priority,
            'budget_allocation': ch.budget_allocation,
            'existing_presence': ch.existing_presence,
            'strategy_notes': ch.strategy_notes,
        })

    # Competitors
    data['competitors'] = []
    for comp in config.competitors:
        data['competitors'].append({
            'name': comp.name,
            'positioning': comp.positioning,
            'pricing': comp.pricing,
            'strengths': comp.strengths,
            'weaknesses': comp.weaknesses,
            'market_share': comp.market_share,
        })

    # Simulation
    data['simulation'] = {
        'cycles': config.simulation.cycles,
        'buyer_agents': config.simulation.buyer_agents,
        'competitor_agents': config.simulation.competitor_agents,
        'channel_agents': config.simulation.channel_agents,
        'cycle_unit': config.simulation.cycle_unit,
        'randomness': config.simulation.randomness,
    }

    return data
